// atomics_full.cpp — GENERATED by tools/gen_atomics.py. Emits every atomic op.
#define _CRT_SECURE_NO_WARNINGS
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>
#include <wasmp/wasmp.hpp>
using namespace wasmp;
using Fn = FunctionEmitter<policy::Trust>;
int main() {
    Features feat = Features::Core();
    feat.atomics = true;
    Module mod(feat);
    mod.Memory(MemLimits{.min = 1, .max = 1, .shared = true});
    TypeIdx vsig = mod.FuncTypeOf<void()>();
    std::vector<FuncIdx> ids;
    for (int i = 0; i < 67; ++i) ids.push_back(mod.DeclareFunction(vsig));
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.MemoryAtomicNotify();
        fn.Drop();
        mod.DefineFunction(ids[0], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.MemoryAtomicWait32();
        fn.Drop();
        mod.DefineFunction(ids[1], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64Const(0);
        fn.MemoryAtomicWait64();
        fn.Drop();
        mod.DefineFunction(ids[2], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.AtomicFence();
        mod.DefineFunction(ids[3], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32AtomicLoad();
        fn.Drop();
        mod.DefineFunction(ids[4], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64AtomicLoad();
        fn.Drop();
        mod.DefineFunction(ids[5], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32AtomicLoad8U();
        fn.Drop();
        mod.DefineFunction(ids[6], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32AtomicLoad16U();
        fn.Drop();
        mod.DefineFunction(ids[7], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64AtomicLoad8U();
        fn.Drop();
        mod.DefineFunction(ids[8], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64AtomicLoad16U();
        fn.Drop();
        mod.DefineFunction(ids[9], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64AtomicLoad32U();
        fn.Drop();
        mod.DefineFunction(ids[10], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicStore();
        mod.DefineFunction(ids[11], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicStore();
        mod.DefineFunction(ids[12], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicStore8();
        mod.DefineFunction(ids[13], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicStore16();
        mod.DefineFunction(ids[14], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicStore8();
        mod.DefineFunction(ids[15], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicStore16();
        mod.DefineFunction(ids[16], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicStore32();
        mod.DefineFunction(ids[17], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmwAdd();
        fn.Drop();
        mod.DefineFunction(ids[18], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw8AddU();
        fn.Drop();
        mod.DefineFunction(ids[19], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw16AddU();
        fn.Drop();
        mod.DefineFunction(ids[20], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmwAdd();
        fn.Drop();
        mod.DefineFunction(ids[21], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw8AddU();
        fn.Drop();
        mod.DefineFunction(ids[22], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw16AddU();
        fn.Drop();
        mod.DefineFunction(ids[23], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw32AddU();
        fn.Drop();
        mod.DefineFunction(ids[24], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmwSub();
        fn.Drop();
        mod.DefineFunction(ids[25], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw8SubU();
        fn.Drop();
        mod.DefineFunction(ids[26], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw16SubU();
        fn.Drop();
        mod.DefineFunction(ids[27], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmwSub();
        fn.Drop();
        mod.DefineFunction(ids[28], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw8SubU();
        fn.Drop();
        mod.DefineFunction(ids[29], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw16SubU();
        fn.Drop();
        mod.DefineFunction(ids[30], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw32SubU();
        fn.Drop();
        mod.DefineFunction(ids[31], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmwAnd();
        fn.Drop();
        mod.DefineFunction(ids[32], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw8AndU();
        fn.Drop();
        mod.DefineFunction(ids[33], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw16AndU();
        fn.Drop();
        mod.DefineFunction(ids[34], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmwAnd();
        fn.Drop();
        mod.DefineFunction(ids[35], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw8AndU();
        fn.Drop();
        mod.DefineFunction(ids[36], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw16AndU();
        fn.Drop();
        mod.DefineFunction(ids[37], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw32AndU();
        fn.Drop();
        mod.DefineFunction(ids[38], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmwOr();
        fn.Drop();
        mod.DefineFunction(ids[39], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw8OrU();
        fn.Drop();
        mod.DefineFunction(ids[40], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw16OrU();
        fn.Drop();
        mod.DefineFunction(ids[41], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmwOr();
        fn.Drop();
        mod.DefineFunction(ids[42], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw8OrU();
        fn.Drop();
        mod.DefineFunction(ids[43], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw16OrU();
        fn.Drop();
        mod.DefineFunction(ids[44], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw32OrU();
        fn.Drop();
        mod.DefineFunction(ids[45], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmwXor();
        fn.Drop();
        mod.DefineFunction(ids[46], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw8XorU();
        fn.Drop();
        mod.DefineFunction(ids[47], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw16XorU();
        fn.Drop();
        mod.DefineFunction(ids[48], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmwXor();
        fn.Drop();
        mod.DefineFunction(ids[49], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw8XorU();
        fn.Drop();
        mod.DefineFunction(ids[50], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw16XorU();
        fn.Drop();
        mod.DefineFunction(ids[51], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw32XorU();
        fn.Drop();
        mod.DefineFunction(ids[52], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmwXchg();
        fn.Drop();
        mod.DefineFunction(ids[53], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw8XchgU();
        fn.Drop();
        mod.DefineFunction(ids[54], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw16XchgU();
        fn.Drop();
        mod.DefineFunction(ids[55], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmwXchg();
        fn.Drop();
        mod.DefineFunction(ids[56], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw8XchgU();
        fn.Drop();
        mod.DefineFunction(ids[57], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw16XchgU();
        fn.Drop();
        mod.DefineFunction(ids[58], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw32XchgU();
        fn.Drop();
        mod.DefineFunction(ids[59], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmwCmpxchg();
        fn.Drop();
        mod.DefineFunction(ids[60], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw8CmpxchgU();
        fn.Drop();
        mod.DefineFunction(ids[61], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32Const(0);
        fn.I32AtomicRmw16CmpxchgU();
        fn.Drop();
        mod.DefineFunction(ids[62], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmwCmpxchg();
        fn.Drop();
        mod.DefineFunction(ids[63], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw8CmpxchgU();
        fn.Drop();
        mod.DefineFunction(ids[64], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw16CmpxchgU();
        fn.Drop();
        mod.DefineFunction(ids[65], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I64Const(0);
        fn.I64Const(0);
        fn.I64AtomicRmw32CmpxchgU();
        fn.Drop();
        mod.DefineFunction(ids[66], fn.Finish()); }
    auto bytes = mod.Assemble();
    if (const char* dir = std::getenv("WASMP_GOLDEN_DIR")) {
        std::string full = std::string(dir) + "/atomics_full.wasm";
        if (FILE* f = std::fopen(full.c_str(), "wb")) { std::fwrite(bytes.data(), 1, bytes.size(), f); std::fclose(f); }
    }
    std::printf("emitted %d atomic ops, %zu bytes", 67, bytes.size());
    return 0;
}
