// simd_full.cpp — GENERATED by tools/gen_simd.py. Emits every SIMD instruction
// through the library into one module; the external wasm-tools leg validates it.
#define _CRT_SECURE_NO_WARNINGS
#include <array>
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>
#include <wasmp/wasmp.hpp>
using namespace wasmp;
using Fn = FunctionEmitter<policy::Trust>;
int main() {
    Features feat = Features::All();
    feat.memory64 = false;  // keep i32 addresses for the SIMD memory ops
    Module mod(feat);
    mod.Memory(MemLimits{.min = 1});
    TypeIdx vsig = mod.FuncTypeOf<void()>();
    std::vector<FuncIdx> ids;
    for (int i = 0; i < 236; ++i) ids.push_back(mod.DeclareFunction(vsig));
    const std::array<u8, 16> z{};
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load();
        fn.Drop();
        mod.DefineFunction(ids[0], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load8x8S();
        fn.Drop();
        mod.DefineFunction(ids[1], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load8x8U();
        fn.Drop();
        mod.DefineFunction(ids[2], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load16x4S();
        fn.Drop();
        mod.DefineFunction(ids[3], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load16x4U();
        fn.Drop();
        mod.DefineFunction(ids[4], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load32x2S();
        fn.Drop();
        mod.DefineFunction(ids[5], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load32x2U();
        fn.Drop();
        mod.DefineFunction(ids[6], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load8Splat();
        fn.Drop();
        mod.DefineFunction(ids[7], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load16Splat();
        fn.Drop();
        mod.DefineFunction(ids[8], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load32Splat();
        fn.Drop();
        mod.DefineFunction(ids[9], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load64Splat();
        fn.Drop();
        mod.DefineFunction(ids[10], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load32Zero();
        fn.Drop();
        mod.DefineFunction(ids[11], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Load64Zero();
        fn.Drop();
        mod.DefineFunction(ids[12], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Const(z);
        fn.V128Store();
        mod.DefineFunction(ids[13], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Const(z);
        fn.V128Load8Lane(MemArg{}, 0);
        fn.Drop();
        mod.DefineFunction(ids[14], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Const(z);
        fn.V128Load16Lane(MemArg{}, 0);
        fn.Drop();
        mod.DefineFunction(ids[15], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Const(z);
        fn.V128Load32Lane(MemArg{}, 0);
        fn.Drop();
        mod.DefineFunction(ids[16], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Const(z);
        fn.V128Load64Lane(MemArg{}, 0);
        fn.Drop();
        mod.DefineFunction(ids[17], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Const(z);
        fn.V128Store8Lane(MemArg{}, 0);
        mod.DefineFunction(ids[18], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Const(z);
        fn.V128Store16Lane(MemArg{}, 0);
        mod.DefineFunction(ids[19], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Const(z);
        fn.V128Store32Lane(MemArg{}, 0);
        mod.DefineFunction(ids[20], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.V128Const(z);
        fn.V128Store64Lane(MemArg{}, 0);
        mod.DefineFunction(ids[21], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.Drop();
        mod.DefineFunction(ids[22], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16Shuffle(z);
        fn.Drop();
        mod.DefineFunction(ids[23], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16Swizzle();
        fn.Drop();
        mod.DefineFunction(ids[24], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I8x16Splat();
        fn.Drop();
        mod.DefineFunction(ids[25], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I16x8Splat();
        fn.Drop();
        mod.DefineFunction(ids[26], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I32Const(0);
        fn.I32x4Splat();
        fn.Drop();
        mod.DefineFunction(ids[27], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.I64Const(0);
        fn.I64x2Splat();
        fn.Drop();
        mod.DefineFunction(ids[28], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.F32Const(0);
        fn.F32x4Splat();
        fn.Drop();
        mod.DefineFunction(ids[29], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.F64Const(0);
        fn.F64x2Splat();
        fn.Drop();
        mod.DefineFunction(ids[30], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I8x16ExtractLaneS(0);
        fn.Drop();
        mod.DefineFunction(ids[31], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I8x16ExtractLaneU(0);
        fn.Drop();
        mod.DefineFunction(ids[32], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I8x16ReplaceLane(0);
        fn.Drop();
        mod.DefineFunction(ids[33], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8ExtractLaneS(0);
        fn.Drop();
        mod.DefineFunction(ids[34], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8ExtractLaneU(0);
        fn.Drop();
        mod.DefineFunction(ids[35], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I16x8ReplaceLane(0);
        fn.Drop();
        mod.DefineFunction(ids[36], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4ExtractLane(0);
        fn.Drop();
        mod.DefineFunction(ids[37], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I32x4ReplaceLane(0);
        fn.Drop();
        mod.DefineFunction(ids[38], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I64x2ExtractLane(0);
        fn.Drop();
        mod.DefineFunction(ids[39], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I64Const(0);
        fn.I64x2ReplaceLane(0);
        fn.Drop();
        mod.DefineFunction(ids[40], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4ExtractLane(0);
        fn.Drop();
        mod.DefineFunction(ids[41], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32Const(0);
        fn.F32x4ReplaceLane(0);
        fn.Drop();
        mod.DefineFunction(ids[42], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2ExtractLane(0);
        fn.Drop();
        mod.DefineFunction(ids[43], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64Const(0);
        fn.F64x2ReplaceLane(0);
        fn.Drop();
        mod.DefineFunction(ids[44], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16Eq();
        fn.Drop();
        mod.DefineFunction(ids[45], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16Ne();
        fn.Drop();
        mod.DefineFunction(ids[46], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16LtS();
        fn.Drop();
        mod.DefineFunction(ids[47], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16LtU();
        fn.Drop();
        mod.DefineFunction(ids[48], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16GtS();
        fn.Drop();
        mod.DefineFunction(ids[49], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16GtU();
        fn.Drop();
        mod.DefineFunction(ids[50], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16LeS();
        fn.Drop();
        mod.DefineFunction(ids[51], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16LeU();
        fn.Drop();
        mod.DefineFunction(ids[52], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16GeS();
        fn.Drop();
        mod.DefineFunction(ids[53], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16GeU();
        fn.Drop();
        mod.DefineFunction(ids[54], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8Eq();
        fn.Drop();
        mod.DefineFunction(ids[55], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8Ne();
        fn.Drop();
        mod.DefineFunction(ids[56], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8LtS();
        fn.Drop();
        mod.DefineFunction(ids[57], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8LtU();
        fn.Drop();
        mod.DefineFunction(ids[58], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8GtS();
        fn.Drop();
        mod.DefineFunction(ids[59], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8GtU();
        fn.Drop();
        mod.DefineFunction(ids[60], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8LeS();
        fn.Drop();
        mod.DefineFunction(ids[61], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8LeU();
        fn.Drop();
        mod.DefineFunction(ids[62], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8GeS();
        fn.Drop();
        mod.DefineFunction(ids[63], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8GeU();
        fn.Drop();
        mod.DefineFunction(ids[64], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4Eq();
        fn.Drop();
        mod.DefineFunction(ids[65], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4Ne();
        fn.Drop();
        mod.DefineFunction(ids[66], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4LtS();
        fn.Drop();
        mod.DefineFunction(ids[67], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4LtU();
        fn.Drop();
        mod.DefineFunction(ids[68], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4GtS();
        fn.Drop();
        mod.DefineFunction(ids[69], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4GtU();
        fn.Drop();
        mod.DefineFunction(ids[70], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4LeS();
        fn.Drop();
        mod.DefineFunction(ids[71], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4LeU();
        fn.Drop();
        mod.DefineFunction(ids[72], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4GeS();
        fn.Drop();
        mod.DefineFunction(ids[73], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4GeU();
        fn.Drop();
        mod.DefineFunction(ids[74], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2Eq();
        fn.Drop();
        mod.DefineFunction(ids[75], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2Ne();
        fn.Drop();
        mod.DefineFunction(ids[76], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2LtS();
        fn.Drop();
        mod.DefineFunction(ids[77], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2GtS();
        fn.Drop();
        mod.DefineFunction(ids[78], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2LeS();
        fn.Drop();
        mod.DefineFunction(ids[79], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2GeS();
        fn.Drop();
        mod.DefineFunction(ids[80], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Eq();
        fn.Drop();
        mod.DefineFunction(ids[81], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Ne();
        fn.Drop();
        mod.DefineFunction(ids[82], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Lt();
        fn.Drop();
        mod.DefineFunction(ids[83], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Gt();
        fn.Drop();
        mod.DefineFunction(ids[84], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Le();
        fn.Drop();
        mod.DefineFunction(ids[85], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Ge();
        fn.Drop();
        mod.DefineFunction(ids[86], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Eq();
        fn.Drop();
        mod.DefineFunction(ids[87], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Ne();
        fn.Drop();
        mod.DefineFunction(ids[88], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Lt();
        fn.Drop();
        mod.DefineFunction(ids[89], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Gt();
        fn.Drop();
        mod.DefineFunction(ids[90], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Le();
        fn.Drop();
        mod.DefineFunction(ids[91], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Ge();
        fn.Drop();
        mod.DefineFunction(ids[92], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Not();
        fn.Drop();
        mod.DefineFunction(ids[93], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.V128And();
        fn.Drop();
        mod.DefineFunction(ids[94], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.V128Andnot();
        fn.Drop();
        mod.DefineFunction(ids[95], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.V128Or();
        fn.Drop();
        mod.DefineFunction(ids[96], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.V128Xor();
        fn.Drop();
        mod.DefineFunction(ids[97], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.V128Bitselect();
        fn.Drop();
        mod.DefineFunction(ids[98], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128AnyTrue();
        fn.Drop();
        mod.DefineFunction(ids[99], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I8x16Abs();
        fn.Drop();
        mod.DefineFunction(ids[100], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I8x16Neg();
        fn.Drop();
        mod.DefineFunction(ids[101], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I8x16Popcnt();
        fn.Drop();
        mod.DefineFunction(ids[102], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I8x16AllTrue();
        fn.Drop();
        mod.DefineFunction(ids[103], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I8x16Bitmask();
        fn.Drop();
        mod.DefineFunction(ids[104], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16NarrowI16x8S();
        fn.Drop();
        mod.DefineFunction(ids[105], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16NarrowI16x8U();
        fn.Drop();
        mod.DefineFunction(ids[106], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I8x16Shl();
        fn.Drop();
        mod.DefineFunction(ids[107], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I8x16ShrS();
        fn.Drop();
        mod.DefineFunction(ids[108], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I8x16ShrU();
        fn.Drop();
        mod.DefineFunction(ids[109], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16Add();
        fn.Drop();
        mod.DefineFunction(ids[110], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16AddSatS();
        fn.Drop();
        mod.DefineFunction(ids[111], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16AddSatU();
        fn.Drop();
        mod.DefineFunction(ids[112], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16Sub();
        fn.Drop();
        mod.DefineFunction(ids[113], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16SubSatS();
        fn.Drop();
        mod.DefineFunction(ids[114], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16SubSatU();
        fn.Drop();
        mod.DefineFunction(ids[115], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16MinS();
        fn.Drop();
        mod.DefineFunction(ids[116], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16MinU();
        fn.Drop();
        mod.DefineFunction(ids[117], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16MaxS();
        fn.Drop();
        mod.DefineFunction(ids[118], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16MaxU();
        fn.Drop();
        mod.DefineFunction(ids[119], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I8x16AvgrU();
        fn.Drop();
        mod.DefineFunction(ids[120], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8ExtaddPairwiseI8x16S();
        fn.Drop();
        mod.DefineFunction(ids[121], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8ExtaddPairwiseI8x16U();
        fn.Drop();
        mod.DefineFunction(ids[122], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8Abs();
        fn.Drop();
        mod.DefineFunction(ids[123], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8Neg();
        fn.Drop();
        mod.DefineFunction(ids[124], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8Q15mulrSatS();
        fn.Drop();
        mod.DefineFunction(ids[125], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8AllTrue();
        fn.Drop();
        mod.DefineFunction(ids[126], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8Bitmask();
        fn.Drop();
        mod.DefineFunction(ids[127], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8NarrowI32x4S();
        fn.Drop();
        mod.DefineFunction(ids[128], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8NarrowI32x4U();
        fn.Drop();
        mod.DefineFunction(ids[129], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8ExtendLowI8x16S();
        fn.Drop();
        mod.DefineFunction(ids[130], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8ExtendHighI8x16S();
        fn.Drop();
        mod.DefineFunction(ids[131], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8ExtendLowI8x16U();
        fn.Drop();
        mod.DefineFunction(ids[132], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I16x8ExtendHighI8x16U();
        fn.Drop();
        mod.DefineFunction(ids[133], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I16x8Shl();
        fn.Drop();
        mod.DefineFunction(ids[134], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I16x8ShrS();
        fn.Drop();
        mod.DefineFunction(ids[135], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I16x8ShrU();
        fn.Drop();
        mod.DefineFunction(ids[136], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8Add();
        fn.Drop();
        mod.DefineFunction(ids[137], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8AddSatS();
        fn.Drop();
        mod.DefineFunction(ids[138], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8AddSatU();
        fn.Drop();
        mod.DefineFunction(ids[139], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8Sub();
        fn.Drop();
        mod.DefineFunction(ids[140], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8SubSatS();
        fn.Drop();
        mod.DefineFunction(ids[141], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8SubSatU();
        fn.Drop();
        mod.DefineFunction(ids[142], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8Mul();
        fn.Drop();
        mod.DefineFunction(ids[143], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8MinS();
        fn.Drop();
        mod.DefineFunction(ids[144], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8MinU();
        fn.Drop();
        mod.DefineFunction(ids[145], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8MaxS();
        fn.Drop();
        mod.DefineFunction(ids[146], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8MaxU();
        fn.Drop();
        mod.DefineFunction(ids[147], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8AvgrU();
        fn.Drop();
        mod.DefineFunction(ids[148], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8ExtmulLowI8x16S();
        fn.Drop();
        mod.DefineFunction(ids[149], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8ExtmulHighI8x16S();
        fn.Drop();
        mod.DefineFunction(ids[150], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8ExtmulLowI8x16U();
        fn.Drop();
        mod.DefineFunction(ids[151], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I16x8ExtmulHighI8x16U();
        fn.Drop();
        mod.DefineFunction(ids[152], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4ExtaddPairwiseI16x8S();
        fn.Drop();
        mod.DefineFunction(ids[153], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4ExtaddPairwiseI16x8U();
        fn.Drop();
        mod.DefineFunction(ids[154], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4Abs();
        fn.Drop();
        mod.DefineFunction(ids[155], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4Neg();
        fn.Drop();
        mod.DefineFunction(ids[156], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4AllTrue();
        fn.Drop();
        mod.DefineFunction(ids[157], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4Bitmask();
        fn.Drop();
        mod.DefineFunction(ids[158], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4ExtendLowI16x8S();
        fn.Drop();
        mod.DefineFunction(ids[159], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4ExtendHighI16x8S();
        fn.Drop();
        mod.DefineFunction(ids[160], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4ExtendLowI16x8U();
        fn.Drop();
        mod.DefineFunction(ids[161], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4ExtendHighI16x8U();
        fn.Drop();
        mod.DefineFunction(ids[162], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I32x4Shl();
        fn.Drop();
        mod.DefineFunction(ids[163], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I32x4ShrS();
        fn.Drop();
        mod.DefineFunction(ids[164], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I32x4ShrU();
        fn.Drop();
        mod.DefineFunction(ids[165], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4Add();
        fn.Drop();
        mod.DefineFunction(ids[166], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4Sub();
        fn.Drop();
        mod.DefineFunction(ids[167], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4Mul();
        fn.Drop();
        mod.DefineFunction(ids[168], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4MinS();
        fn.Drop();
        mod.DefineFunction(ids[169], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4MinU();
        fn.Drop();
        mod.DefineFunction(ids[170], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4MaxS();
        fn.Drop();
        mod.DefineFunction(ids[171], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4MaxU();
        fn.Drop();
        mod.DefineFunction(ids[172], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4DotI16x8S();
        fn.Drop();
        mod.DefineFunction(ids[173], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4ExtmulLowI16x8S();
        fn.Drop();
        mod.DefineFunction(ids[174], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4ExtmulHighI16x8S();
        fn.Drop();
        mod.DefineFunction(ids[175], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4ExtmulLowI16x8U();
        fn.Drop();
        mod.DefineFunction(ids[176], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I32x4ExtmulHighI16x8U();
        fn.Drop();
        mod.DefineFunction(ids[177], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I64x2Abs();
        fn.Drop();
        mod.DefineFunction(ids[178], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I64x2Neg();
        fn.Drop();
        mod.DefineFunction(ids[179], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I64x2AllTrue();
        fn.Drop();
        mod.DefineFunction(ids[180], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I64x2Bitmask();
        fn.Drop();
        mod.DefineFunction(ids[181], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I64x2ExtendLowI32x4S();
        fn.Drop();
        mod.DefineFunction(ids[182], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I64x2ExtendHighI32x4S();
        fn.Drop();
        mod.DefineFunction(ids[183], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I64x2ExtendLowI32x4U();
        fn.Drop();
        mod.DefineFunction(ids[184], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I64x2ExtendHighI32x4U();
        fn.Drop();
        mod.DefineFunction(ids[185], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I64x2Shl();
        fn.Drop();
        mod.DefineFunction(ids[186], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I64x2ShrS();
        fn.Drop();
        mod.DefineFunction(ids[187], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32Const(0);
        fn.I64x2ShrU();
        fn.Drop();
        mod.DefineFunction(ids[188], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2Add();
        fn.Drop();
        mod.DefineFunction(ids[189], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2Sub();
        fn.Drop();
        mod.DefineFunction(ids[190], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2Mul();
        fn.Drop();
        mod.DefineFunction(ids[191], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2ExtmulLowI32x4S();
        fn.Drop();
        mod.DefineFunction(ids[192], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2ExtmulHighI32x4S();
        fn.Drop();
        mod.DefineFunction(ids[193], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2ExtmulLowI32x4U();
        fn.Drop();
        mod.DefineFunction(ids[194], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.I64x2ExtmulHighI32x4U();
        fn.Drop();
        mod.DefineFunction(ids[195], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4Ceil();
        fn.Drop();
        mod.DefineFunction(ids[196], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4Floor();
        fn.Drop();
        mod.DefineFunction(ids[197], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4Trunc();
        fn.Drop();
        mod.DefineFunction(ids[198], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4Nearest();
        fn.Drop();
        mod.DefineFunction(ids[199], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4Abs();
        fn.Drop();
        mod.DefineFunction(ids[200], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4Neg();
        fn.Drop();
        mod.DefineFunction(ids[201], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4Sqrt();
        fn.Drop();
        mod.DefineFunction(ids[202], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Add();
        fn.Drop();
        mod.DefineFunction(ids[203], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Sub();
        fn.Drop();
        mod.DefineFunction(ids[204], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Mul();
        fn.Drop();
        mod.DefineFunction(ids[205], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Div();
        fn.Drop();
        mod.DefineFunction(ids[206], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Min();
        fn.Drop();
        mod.DefineFunction(ids[207], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Max();
        fn.Drop();
        mod.DefineFunction(ids[208], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Pmin();
        fn.Drop();
        mod.DefineFunction(ids[209], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F32x4Pmax();
        fn.Drop();
        mod.DefineFunction(ids[210], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2Ceil();
        fn.Drop();
        mod.DefineFunction(ids[211], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2Floor();
        fn.Drop();
        mod.DefineFunction(ids[212], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2Trunc();
        fn.Drop();
        mod.DefineFunction(ids[213], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2Nearest();
        fn.Drop();
        mod.DefineFunction(ids[214], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2Abs();
        fn.Drop();
        mod.DefineFunction(ids[215], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2Neg();
        fn.Drop();
        mod.DefineFunction(ids[216], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2Sqrt();
        fn.Drop();
        mod.DefineFunction(ids[217], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Add();
        fn.Drop();
        mod.DefineFunction(ids[218], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Sub();
        fn.Drop();
        mod.DefineFunction(ids[219], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Mul();
        fn.Drop();
        mod.DefineFunction(ids[220], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Div();
        fn.Drop();
        mod.DefineFunction(ids[221], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Min();
        fn.Drop();
        mod.DefineFunction(ids[222], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Max();
        fn.Drop();
        mod.DefineFunction(ids[223], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Pmin();
        fn.Drop();
        mod.DefineFunction(ids[224], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.V128Const(z);
        fn.F64x2Pmax();
        fn.Drop();
        mod.DefineFunction(ids[225], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4TruncSatF32x4S();
        fn.Drop();
        mod.DefineFunction(ids[226], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4TruncSatF32x4U();
        fn.Drop();
        mod.DefineFunction(ids[227], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4ConvertI32x4S();
        fn.Drop();
        mod.DefineFunction(ids[228], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4ConvertI32x4U();
        fn.Drop();
        mod.DefineFunction(ids[229], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4TruncSatF64x2SZero();
        fn.Drop();
        mod.DefineFunction(ids[230], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.I32x4TruncSatF64x2UZero();
        fn.Drop();
        mod.DefineFunction(ids[231], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2ConvertLowI32x4S();
        fn.Drop();
        mod.DefineFunction(ids[232], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2ConvertLowI32x4U();
        fn.Drop();
        mod.DefineFunction(ids[233], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F32x4DemoteF64x2Zero();
        fn.Drop();
        mod.DefineFunction(ids[234], fn.Finish()); }
    { Fn fn(mod, vsig);
        fn.V128Const(z);
        fn.F64x2PromoteLowF32x4();
        fn.Drop();
        mod.DefineFunction(ids[235], fn.Finish()); }
    auto bytes = mod.Assemble();
    if (const char* dir = std::getenv("WASMP_GOLDEN_DIR")) {
        std::string full = std::string(dir) + "/simd_full.wasm";
        if (FILE* f = std::fopen(full.c_str(), "wb")) {
            std::fwrite(bytes.data(), 1, bytes.size(), f); std::fclose(f);
        }
    }
    std::printf("emitted %d SIMD ops, %zu bytes\n", 236, bytes.size());
    return 0;
}
