#!/usr/bin/env python3
# Authoritatively derive the WASM threads/atomics (0xFE) opcode table, the same
# way as gen_simd.py: author the mnemonics (wasm-tools validates spelling +
# operand types + shared memory + natural alignment when it assembles), read
# the real sub-opcodes back out, and emit the instructions.inc rows plus a
# whole-table emission test.
import re, subprocess, sys, os

WT = os.path.expanduser(r"~/.cargo/bin/wasm-tools.exe")

MNEMONICS = ['memory.atomic.notify', 'memory.atomic.wait32', 'memory.atomic.wait64', 'atomic.fence']
MNEMONICS += ['i32.atomic.load', 'i64.atomic.load', 'i32.atomic.load8_u', 'i32.atomic.load16_u',
              'i64.atomic.load8_u', 'i64.atomic.load16_u', 'i64.atomic.load32_u']
MNEMONICS += ['i32.atomic.store', 'i64.atomic.store', 'i32.atomic.store8', 'i32.atomic.store16',
              'i64.atomic.store8', 'i64.atomic.store16', 'i64.atomic.store32']
for op in ['add', 'sub', 'and', 'or', 'xor', 'xchg']:
    MNEMONICS += [f'i32.atomic.rmw.{op}', f'i32.atomic.rmw8.{op}_u', f'i32.atomic.rmw16.{op}_u',
                  f'i64.atomic.rmw.{op}', f'i64.atomic.rmw8.{op}_u', f'i64.atomic.rmw16.{op}_u',
                  f'i64.atomic.rmw32.{op}_u']
MNEMONICS += ['i32.atomic.rmw.cmpxchg', 'i32.atomic.rmw8.cmpxchg_u', 'i32.atomic.rmw16.cmpxchg_u',
              'i64.atomic.rmw.cmpxchg', 'i64.atomic.rmw8.cmpxchg_u', 'i64.atomic.rmw16.cmpxchg_u',
              'i64.atomic.rmw32.cmpxchg_u']

# type codes: i=i32 I=i64
def sig(m):
    if 'fence' in m: return ('', '', 'fence')
    if 'notify' in m: return ('ii', 'i', 'memarg')
    if 'wait32' in m: return ('iiI', 'i', 'memarg')
    if 'wait64' in m: return ('iII', 'i', 'memarg')
    val = 'I' if m.startswith('i64') else 'i'
    kind = m.split('.')[2]
    if kind.startswith('load'): return ('i', val, 'memarg')
    if kind.startswith('store'): return ('i' + val, '', 'memarg')
    opname = m.split('.')[3]
    if opname.startswith('cmpxchg'): return ('i' + val + val, val, 'memarg')
    return ('i' + val, val, 'memarg')  # rmw add/sub/and/or/xor/xchg

def natural(m):
    if 'wait64' in m: return 3
    if 'notify' in m or 'wait32' in m: return 2
    w = re.search(r'(?:load|store|rmw)(\d+)?', m).group(1)
    if w == '8': return 0
    if w == '16': return 1
    if w == '32': return 2
    return 3 if m.startswith('i64') else 2  # full width

def pascal(m):
    return ''.join(w[:1].upper() + w[1:] for w in m.replace('.', '_').split('_'))

TYPE = {'i': 'I32', 'I': 'I64'}
PARAM = {'i': 'local.get 0', 'I': 'local.get 1'}

def wat_body(m):
    pops, pushes, shape = sig(m)
    lines = [PARAM[t] for t in pops]
    lines.append(m)  # natural align implied
    lines += ['drop'] * len(pushes)
    return '\n    '.join(lines)

funcs = [f'  (func (param i32 i64)\n    {wat_body(m)})' for m in MNEMONICS]
wat = '(module\n  (memory 1 1 shared)\n' + '\n'.join(funcs) + '\n)\n'
open("C:/tmp/atomics_all.wat", "w").write(wat)

r = subprocess.run([WT, 'parse', 'C:/tmp/atomics_all.wat', '-o', 'C:/tmp/atomics_all.wasm'],
                   capture_output=True, text=True)
if r.returncode != 0:
    sys.stderr.write(r.stderr)
    raise SystemExit('parse failed')

data = open("C:/tmp/atomics_all.wasm", 'rb').read()
def rdu(b, p):
    v = s = 0
    while True:
        x = b[p]; p += 1; v |= (x & 0x7f) << s; s += 7
        if not (x & 0x80): return v, p
p = 8; code = None
while p < len(data):
    sid = data[p]; p += 1; size, p = rdu(data, p)
    if sid == 10: code = data[p:p + size]; break
    p += size
ops = []
q = 0; n, q = rdu(code, q)
for _ in range(n):
    bs, q = rdu(code, q); body = code[q:q + bs]; q += bs
    i = body.find(0xFE)
    sub, _ = rdu(body, i + 1)
    ops.append(sub)
assert len(ops) == len(MNEMONICS)

rows = []
for m, sub in zip(MNEMONICS, ops):
    pops, pushes, shape = sig(m)
    name = pascal(m)
    shp = 'FENCE' if shape == 'fence' else f'MEMARG({natural(m)})'
    eff = '(' + ', '.join(TYPE[t] for t in pops) + ') -> (' + ', '.join(TYPE[t] for t in pushes) + ')'
    rows.append((name, f'WASMP_PFX(0xFE,{sub})', shp, eff))
w1 = max(len(r[0]) for r in rows); w2 = max(len(r[1]) for r in rows); w3 = max(len(r[2]) for r in rows)
with open("C:/tmp/atomics_rows.inc", "w") as f:
    for name, opc, shp, eff in rows:
        f.write(f'WASMP_OP({name+",":<{w1+1}} {opc+",":<{w2+1}} {shp+",":<{w3+1}} {eff+",":<24} ATOMICS)\n')

# Emission test.
blocks = []
for i, m in enumerate(MNEMONICS):
    pops, pushes, shape = sig(m)
    body = ''.join('        ' + ('fn.I32Const(0);' if t == 'i' else 'fn.I64Const(0);') + '\n' for t in pops)
    body += '        fn.' + pascal(m) + '();\n'
    body += ''.join('        fn.Drop();\n' for _ in pushes)
    blocks.append(f'    {{ Fn fn(mod, vsig);\n{body}        mod.DefineFunction(ids[{i}], fn.Finish()); }}')
cpp = '''// atomics_full.cpp — GENERATED by tools/gen_atomics.py. Emits every atomic op.
#define _CRT_SECURE_NO_WARNINGS
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>
#include <wasmp/wasmp.hpp>
using namespace wasmp;
using Fn = FunctionEmitter<policy::Trust>;
int main() {
    Features feat = Features::Core();
    feat.atomics = true;
    Module mod(feat);
    mod.Memory(MemLimits{.min = 1, .max = 1, .shared = true});
    TypeIdx vsig = mod.FuncTypeOf<void()>();
    std::vector<FuncIdx> ids;
    for (int i = 0; i < %d; ++i) ids.push_back(mod.DeclareFunction(vsig));
%s
    auto bytes = mod.Assemble();
    if (const char* dir = std::getenv("WASMP_GOLDEN_DIR")) {
        std::string full = std::string(dir) + "/atomics_full.wasm";
        if (FILE* f = std::fopen(full.c_str(), "wb")) { std::fwrite(bytes.data(), 1, bytes.size(), f); std::fclose(f); }
    }
    std::printf("emitted %%d atomic ops, %%zu bytes", %d, bytes.size());
    return 0;
}
''' % (len(MNEMONICS), '\n'.join(blocks), len(MNEMONICS))
open("C:/Projects/WASMP!/tests/atomics_full.cpp", "w", encoding="utf-8").write(cpp)
print(f"generated {len(rows)} atomic rows; opcode range {min(ops)}..{max(ops)}")
